### ISSUE TITLE
rdfs:domain missing from class properties

### ISSUE THREAD

**Issue by sandervd** [SEMICeu/ADMS-AP#1]
In the ADMS-AP specification published on Joinup at
https://joinup.ec.europa.eu/rdf_entity/http_e_f_fdata_ceuropa_ceu_fw21_f3d6cad22_b1934_b43c3_b81fe_b0a01641b0379

The domains are missing in the property definitions. 
From the comments in the file it is clear where which property goes, but for our implementation we need to be able to query the relations.

**Comment by sandervd** [comment]
As this repository does not contain the actual RDFS file, I can't create a PR here.

The RDFS file with the domains added to the properties:
[adms-ap_v2.01_rdf_schema-1.ttl.txt](https://github.com/SEMICeu/ADMS-AP/files/1720172/adms-ap_v2.01_rdf_schema-1.ttl.txt)

**Comment by idimopoulos** [comment]
I tried the Rdf Converter on http://www.easyrdf.org/converter and I was blocked by the lack of the `rdf:` and `owl:` prefix definitions. I am uploading a fixed version with the headers defined.

Also, there were two miss-typings  where instead of `rdfs:domain` it was `rdfs:domain:`. I fixed these two too.

[ADMS-AP_v1.rdf.txt](https://github.com/SEMICeu/ADMS-AP/files/1720720/ADMS-AP_v1.rdf.txt)

**Comment by makxdekkers** [comment]
@sandervd @idimopoulos I looked at your new proposed RDF file. I am wondering about adding domain axioms to properties in the dct namespace. They are defined by DCMI with undefined domains. Isn't it bad practice to redefine domains and ranges for externally defined terms?

**Comment by akuckartz** [comment]
What exactly are the problems resulting from the "missing" of these domains?

**Comment by sandervd** [comment]
@makxdekkers 
Sorry for the late response, I lost track of this issue:
Indeed, defining the domain property for the external properties will likely cause more problems.

@akuckartz There is now simple no link between the classes and the properties, except that they are published in the same file.
So at the moment we have classes without properties, and a set of dangling properties without classes.

**Comment by makxdekkers** [comment]
No change in the RDF file.
