### ISSUE TITLE
dct:licenseDocument instead of  dct:LicenceDocument

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/ADMS-AP#3]
In the current RDF (2.01) there is a usage of:

dct:LicenceDocument

while there is:

http://www.dublincore.org/documents/dcmi-terms/#terms-LicenseDocument

so there is a typo error in the file

**Comment by makxdekkers** [comment]
Issue has been resolved in bug-fix release published at https://joinup.ec.europa.eu/sites/default/files/distribution/access_url/2018-04/996b8334-9bca-4e3f-b03e-b580e3c442ee/adms-ap_v2.0.2_rdf_schema.ttl.
