### ISSUE TITLE
dct:language value range

### ISSUE THREAD

**Issue by idimopoulos** [SEMICeu/ADMS-AP#5]
This is more of a question than an issue report. I need some clarification on the range of the language term of datasets.

So in ADMS v2, there is the dct:language property declaration for the Dataset:
```
dct:language
    a rdf:Property,    owl:ObjectProperty;
    dct:identifier "dct:language"@en;
    rdfs:comment "Language of the Asset, or language supported by software, using a controlled vocabulary - MDR Languages Named Authority List >> http://publications.europa.eu/resource/authority/language"@en;
    rdfs:isDefinedBy <http://purl.org/dc/terms/>;
    rdfs:label "Asset - language"@en;
    rdfs:range dct:LinguisticSystem;
    vann:usageNote "Recommended Property - 0..n"@en.
```
In the `rdfs:comment` section it is noted that the terms should derive from the MDR Languages Named Authority List (as suggested in https://joinup.ec.europa.eu/discussion/values-dctlanguage if I am not sure).
The MDR Language terms though are instances of the Concept class as the collection is also a ConceptScheme. They are not instances of the LinguisticSystem.

Also, the range is defined as dct:LinguisticSystem which is properly defined (as noted in https://www.w3.org/TR/vocab-dcat/#Property:catalog_language).

As also stated there, ` Resources defined by the Library of Congress (1, 2) SHOULD be used. `.
1 and 2 are links pointing to http://id.loc.gov/vocabulary/iso639-1.html and http://id.loc.gov/vocabulary/iso639-2.html
The issue though is that the terms described there, are also Concepts, not LinguistcSystem instances.

So my question is, whether we can freely point to instances and not explicitly to instances of the LinguisticSystem class.

**Comment by makxdekkers** [comment]
You can point to instances of the MDR Languages NAL, even if they are not explicitly declared to be instances of `dct:LinguisticSystem`. The way I understand it, using one of the URIs of the NAL as the object of `dct:language` implies that that URI can be inferred to represent an instance of the class `dct:LinguisticSystem`. This would only be invalid if there was an explicit statement `owl:disjointWith` between the classes `dct:LinguisticSystem` and `skos:Concept`, and there is not.

**Comment by idimopoulos** [comment]
@makxdekkers thank you for your quick response. I will use this for my future arguments :D
I think this issue can be closed.
